### ISSUE TITLE
El link de la version deployada en el README va a una app de Pomodoro en lugar a la de contabilidad-libros

### ISSUE THREAD

**Issue by fullsnacker** [ferutizi/contabilidad-libros#1]
En el archivo README.md, esta mal direccionado el link a la version deployada:

"Podés utilizarla [ACA](https://easy-pomodoro-one.vercel.app/)"

Este va a una app de pomodoro en lugar a la que deberia ser de contabilidad-libros.

Saludos!

**Comment by ferutizi** [comment]
Gracias, ahi lo modifico. Este proyecto no tiene deploy aun
